### ISSUE TITLE
Add Group Defender Option.

### ISSUE THREAD

**Issue by WaltDisneyWorld** [guidojw/nsadmin-discord#116]
Add a anti group Admin abuse system like https://github.com/polaris-rbx/group-defender

**Comment by guidojw** [comment]
Hi, thanks for the suggestion.
I think a function like this is unnecessary for the bot in the current state. The group that the bot is currently used for has all the group permissions for high ranks disabled and lets those people use all the commands (like /promote, /demote) in the Discord server instead. 
I think that way it'll be seen pretty quickly if someone is admin abusing and thus spamming commands in a channel.

I may however in the future if the API side of this project is in a good state for others to use add a utility function on the backend that lets admins/owners revert group admin logs.
